apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc
  labels:
    storage.ks.io/name: nfs
    storage.ks.io/part-of: kubernets-complete-reference
spec:
  storageClassName: client-nfs 
  accessModes:
    - ReadWriteMany 
  resources:
    requests:
      storage: 1Gi
