apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
  labels:
    storage.ks.io/name: nfs
    storage.ks.io/part-of: kubernets-complete-reference
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
    - ReadWriteOnce
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: client-nfs
  nfs:
    path: /data
    server: 192.168.0.20
    readOnly: no
